apiVersion: v1
kind: Service
metadata:
  name: nginx-service           ## name of the service
spec:
  type: ClusterIP
  selector:
    app: nginx-app              ## it should match the pod label ( it targets the pod )
  ports:
  - protocol: TCP
    port: 80                    ## service port   --> by which the service is exposed
    targetPort: 80              ## container port --> pod exposed port
