apiVersion: v1
kind: Service
metadata:
  name: <service_name>                ## name fo the service
spec:
  selector:
    <key>: <value>                    ## it should match the pod label ( it targets the pod )
  ports:
  - protocol: TCP
    port: <service_port>              ## service port   --> by which the service is exposed
    targetPort: <container_port>      ## container port --> pod exposed port
