apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  # namespace: client-namespace        ## client-namespace
  labels:
    app: client-server
spec:
  containers:
  - name: client-container
    image: alpine
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  # namespace: client-namespace        ## client-namespace
spec:
  type: ClusterIP
  selector:
    app: client-server  # Targets client-pod
  ports:
  - protocol: TCP
    port: 5000          # Service port
    targetPort: 5000    # Pod's exposed port