apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs-match-expressions
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx

      - key: tier
        operator: In
        values:
          - frontend

      - key: environment
        operator: NotIn
        values:
          - dev

  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        environment: prod
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
