apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-emptydir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-emptydir
  template:
    metadata:
      labels:
        app: mongo-emptydir
    spec:
      containers:
      - name: mongo
        image: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: secret123
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        emptyDir: {}