apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: newstorageclass
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-dynamic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: newstorageclass
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-dynamic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-dynamic
  template:
    metadata:
      labels:
        app: mongo-dynamic
    spec:
      containers:
      - name: mongo
        image: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: secret123
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-dynamic-pvc
