apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: newstorageclass
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-statefulset-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo-statefulset
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  serviceName: "mongo-statefulset-service"
  replicas: 3
  selector:
    matchLabels:
      app: mongo-statefulset
      environment: test
  template:
    metadata:
      labels:
        app: mongo-statefulset
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:6.0
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip_all"
            - "--port"
            - "27017"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-statefulset-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-statefulset-storage
      spec:
        storageClassName: "newstorageclass"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi